#!/usr/bin/env bash
# Displays DNS information about subdomains

show_info() {
    ip=$(dig +short "$1.$2" | awk 'NR==1 {print $1}')
    echo "The subdomain $1 is a A record and points to $ip"
}

if [ $# -eq 2 ]; then
    show_info "$2" "$1"
else
    show_info "www" "$1"
    show_info "lb-01" "$1"
    show_info "web-01" "$1"
    show_info "web-02" "$1"
fi
