#!/usr/bin/env bash
# Displays DNS information about subdomains

show_info() {
    record=$(dig "$1.$2" | awk '/IN[[:space:]]+A/ {print $4, $5; exit}')
    type=$(echo "$record" | awk '{print $1}')
    ip=$(echo "$record" | awk '{print $2}')

    echo "The subdomain $1 is a $type record and points to $ip"
}

if [ $# -eq 2 ]; then
    show_info "$2" "$1"
else
    show_info "www" "$1"
    show_info "lb-01" "$1"
    show_info "web-01" "$1"
    show_info "web-02" "$1"
fi
